# Przykładowy workflow dla GitHub Actions
# Skopiuj do .github/workflows/docker.yml jeśli używasz GitHub Actions

name: Docker Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: |
        docker-compose build
    
    - name: Start containers
      run: |
        docker-compose up -d
        sleep 10
    
    - name: Run migrations
      run: |
        docker-compose exec -T app php artisan migrate --force
    
    - name: Run tests
      run: |
        docker-compose exec -T app php artisan test
    
    - name: Stop containers
      run: |
        docker-compose down

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'


